Lambda-School-Labs/labs9-property-management

README.md
=> Adds name to readme

README.md, client/src/App.js, client/src/index.js
=> Updates readme

client/src/App.js, client/src/components/Admin/Admin.js, client/src/components/Admin/Layout/layout.js, client/src/components/Admin/Layout/sidebarAdmin.js
Updates all _client_ **folders to use lowercase** and all **components to use pascal case** (SomeComponent) and adds tenant folders and files.
=> Adds basic skeleton of tenant folders and files and creates a naming convention standard

client/src/App.js
=> Adds payment dir and file to tenant dir

netlify.toml
=> Adds netlify toml for deployment

client/src/App.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js
Adds login and signup components with template code
=> Adds login and signup components with template code

db/migrations/20190108171652_users.js, knexfile.js
Removes cc info from users table
Removes cc info from users table
=> User table updates

client/src/App.js, client/src/components/admin/Admin.js, client/src/components/admin/settings/Settings.js
=> Created admin settings view and route.

package.json, yarn.lock
Adds bcryptjs jsonwebtoken and passport packages
=> Adds bcryptjs jsonwebtoken and passport packages

client/src/components/auth/ForgotPassword.js
Adds forgot password component base
=> Adds forgot password component base

client/src/App.js, client/src/components/auth/AuthStyles.js, client/src/components/auth/ForgotPassword.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js, client/src/components/home/Home.js, client/src/components/home/HomeStyles.js, client/src/components/home/Nav.js
Adds links back home and minor layout style adjustments to auth components
=> Adds links back home and minor layout style adjustments to auth components

db/migrations/20190108171652_users.js, knexfile.js, routes/propertyRoutes.js, routes/usersRoutes.js, routes/workOrderRoutes.js, seeds/createProperties.js, seeds/createUsers.js, server.js
Added Seed files to generate fake users and properties with faker.js
Removed fake data generation endpoints as they are no longer necessary.
Added a property_id key to the users table which will be used for tenant/property relationships.
The property_id will be null for users of type "admin".
New feature (non-breaking change which adds functionality)
Ran `knex:seed run` and checked the database with postman to make sure the database
was properly seeded and returning data
=> Added seeds instead of faker endpoints. Added property_id column to users table

routes/propertyRoutes.js
Added 2 endpoints. One returns the properties owned by an admin.
The other returns the tenants for a given property.
Accessed the endpoints multiple times on postman to make sure the proper data was returned
=> Added 2 endpoints to be used by the properties page

client/src/App.js, client/src/components/admin/Admin.js, client/src/components/admin/layout/SidebarAdmin.js, client/src/components/auth/Authenticate.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js, client/src/components/tenant/Tenant.js, client/src/index.js
Added an Authentication component. It renders the home page along with routes for the Login and Signup pages if the user is not logged in. When logged in, it renders the Admin component and its respective routes. For now its setup so that it logs in automatically when clicking the login button on the Login page. 
Ran the client to make sure it displays the home page and its respective routes.
Made sure the login button caused the Admin component to render
=> Added Authentication component. Home/login/signup pages now showing

client/src/components/home/MobileNav.js, client/src/components/home/Nav.js, client/src/styles/Styles.js
Resolves Nav related console errors and comments out error code until wired up
Fixes #51 
=> Resolves Nav related console errors and comments out error code until wired up

client/src/components/auth/AuthStyles.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js
Adds links for navigating to login or signup via form pages if user is at wrong form
=> Adds links for navigating to login or signup via form pages if user is at wrong form

client/src/App.js, client/src/components/auth/AuthStyles.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js, client/src/components/home/HomeStyles.js, client/src/components/home/Nav.js
Adds more styling to auth pages and trys out material ui basic theme implementation
=> Adds more styling to auth pages and trys out material ui basic theme implementation

client/src/components/admin/billing/Billing.js
added a table and hooked everything up to read from state
=> replaced the address menu with a drop down select

README.md, client/package.json, client/src/App.js, client/src/components/auth/Login.js, client/src/components/auth/Signup.js, client/src/components/firebase/Firebase.js, client/src/components/firebase/FirebaseContext.js, client/src/components/firebase/index.js, client/src/index.js, client/yarn.lock
Google Auth setup with Firebase
- Can log in with Google
- Redirected to admin page after successful login
- No persistence or route protection setup yet
Ran the client and made multiple login attempts to make sure successful login and redirect is made
=> Basic Google Auth setup with Firebase

client/package.json, client/src/components/tenant/Tenant.js, client/src/components/tenant/payments/StripeTest.js, client/yarn.lock
Stripe test component hooked up on frontend and is talking to stripe, todo: stripe backend route
=> Stripe test component hooked up on frontend and is talking to stripe, todo: stripe backend route

routes/usersRoutes.js, routes/workOrderRoutes.js, yarn.lock
endpoint testing: http://localhost:4000/api/work-orders/id
=> Currently testing endpoint query. Getting repeated data.

client/src/components/admin/billing/Billing.js, client/src/components/admin/workorders/WorkOrders.js, client/src/components/auth/LoginPage.js, client/src/components/auth/Signup.js, client/src/components/layout/Footer.js
=> Got rid of most of the console warnings

db/migrations/05_work_orders.js, db/seeds/createWorkOrders.js, routes/workOrderRoutes.js
Displaying tenants name on every work order.
=> Fixed worked orders table.

server.js
Possible bugfix for heroku deployment. Still need to test
=> added a possible fix for heroku error

client/src/components/tenant/testing/TestingEndpoints.js
=> Displaying data from Heroku Postgres DB. AWESOME

client/src/components/session/withAuthentication.js, server.js
protected the endpoints with a firebase token verification check
Ran the server and tried accessing endpoints
=> protected the endpoints with a firebase token verification check

client/src/components/admin/billing/Billing.js, routes/usersRoutes.js
Endpoint for the admin settings view
=> added user info endpoint for the admin settings view

README.md, routes/propertyRoutes.js
**DB Tables**:
* Removed unnecessary fields in users table
* Properties table now references owners by uid
* Tenants table now references users by uid
**Endpoints**
* Added an endpoint for owners to add properties
* Added an endpoint for owners to get all of their properties
* Added an endpoint for owners to get all of their properties and its tenants
Tested the endpoints using postman
=> Improvements to DB tables and editted endpoints

db/migrations/02_house_properties.js, routes/tenantDashboard.js, server.js
created tenant dashboard route and endpoint
=> added office_ph and maintenance_ph columns to house_properties table

db/migrations/02_owners.js, db/migrations/03_house_properties.js, db/migrations/04_tenants.js, db/seeds/01_createUsers.js, routes/propertyRoutes.js, routes/usersRoutes.js
Tweaks to the DB tables and seeds for testing.
=> Tested user endpoints. Everything is working.

client/src/components/tenant/Tenant.js, client/src/components/tenant/maintenance/Maintenance.js, client/src/components/tenant/payments/Payments.js, client/src/components/tenant/settings/Settings.js
Minor tweaks to Maintenance layout.
Added route to tenants/payments.
=> Tenants payment layout done.

client/src/components/admin/Admin.js, client/src/components/admin/workorders/WorkOrders.js
still just rendering dummy data until a few more bugs are fixed
=> pulling in workorder data from server and setting state

client/src/components/tenant/Tenant.js, client/src/components/tenant/dashboard/Dashboard.js
Still needs to be able to get the property information.
Both buttons are working.
=> Tenants dashboard design finished.

client/src/components/admin/tenants/InvitesTable.js, client/src/components/admin/tenants/Tenants.js, client/src/components/auth/SetupPage.js, client/src/components/session/withAuthentication.js, db/migrations/01_users.js, routes/invitationRoutes.js, routes/usersRoutes.js
The tenants page for owners now lets you send an invitation to a tenant and displays pending invites in a table
=> Tenants page

client/src/components/tenant/settings/InviteTable.js, client/src/components/tenant/settings/Settings.js, routes/invitationRoutes.js
Tenant's settings page allows the user to accept invites to connect with owners and updates their DB entry upon accepting
=> Tenant settings page can accept invites

client/src/components/admin/workorders/WorkOrders.js
now able to click the different radio buttons
=> added conditional message if there are no work orders

client/src/components/admin/Admin.js, client/src/components/admin/workorders/FileUploader.css, client/src/components/admin/workorders/FileUploader.js, client/src/components/tenant/maintenance/Maintenance.js
…ommented out till further notice
=> fixes to tenant work orders UI, uppy modal fixed, settings in admin commented out till further notice

client/package.json, client/src/components/admin/dashboard/DashboardPage.js, client/src/components/admin/properties/AddPropertyModal.js, client/src/components/admin/properties/Properties.js, client/src/components/admin/properties/PropertyModal.js, client/src/components/admin/properties/states.js, client/src/components/admin/tenants/InvitesTable.js, client/src/components/admin/tenants/Tenants.js, client/src/components/admin/tenants/TenantsTable.js, client/src/components/admin/workorders/WorkOrders.js, client/src/components/emptypage/EmptyPage.js, client/src/components/loading/Loading.js, client/src/components/textmaskcustom/TextMaskCustom.js, client/yarn.lock, db/migrations/03_house_properties.js, routes/propertyRoutes.js
- Added Progess components to display when pages/components are loading
- Text is displayed in components/pages with no data
- Property phone numbers are now stored as strings
- Add property form now has a custom formatted text input for phone numbers
=> UI/UX improvements to the Admin routes

client/src/components/tenant/dashboard/Dashboard.js, client/src/components/tenant/maintenance/Maintenance.js
Deleted commented code. 
Change address text style. 
Added city, state and zip code to address. 
Changed the GET endpoint.
=> Changes to Tenants Maintenance view

client/src/components/tenant/dashboard/Dashboard.js
=> Alerts card in the tenants dashboard is working now.

client/src/components/tenant/dashboard/Dashboard.js, routes/tenantRoutes.js
Fixed console.log bug by adding a unique key to the work orders.
Added the display_name column to the dashboard backend endpoint.
=> Dashboard's property card is displaying the owner's name.
